109-editdelete-posting-to-be-dynamically
ramy-att/trivial-soen341project2023 pull request #115
Opened 2023-03-23 03:30 UTC by khaled106

Posting page is now full function as the employer is able to Add and delete psoting since the merged PR #. Here we implemented edit postings as user can now edit existing positngs.

2023-03-23 03:34 UTC, mario-elshaer approved these changes
Great work on fixing the modal such that we can now edit or add depending on the need. Code looks neat! Great work all around.

2023-03-23 03:51 UTC, ramy-att requested changes
Nicely done! Great job! Just left a couple of small inline comments.

2023-03-23 03:51 UTC, ramy-att commented on client/src/components/Postings/EditPosting.js
> +        // organizationName: userInfo.organizationName,
If the above comments are not needed you can remove them

2023-03-23 03:51 UTC, ramy-att commented on client/src/components/Postings/EditPosting.js
> +        // history.push("/job-postings");
Same here

2023-03-23 03:51 UTC, ramy-att commented on client/src/components/Postings/EditPosting.js
> +            </Form.Group>
@khaled106 can you please state-control this FormControl, currently if the user sets a custom location it appears as this:
![image](https://user-images.githubusercontent.com/83047251/227098306-a0abd1de-36c8-4c1e-8e43-4f0d53f9a657.png)
We would like to set the location to the custom entered location

2023-03-23 03:51 UTC, ramy-att commented on client/src/components/Postings/Posting.js
> +        </h1>
Nice

2023-03-24 01:30 UTC, ramy-att approved these changes

2023-03-24 01:30 UTC, merged