Sign-in/-Sign-up-Page
ramy-att/trivial-soen341project2023 pull request #35
Opened 2023-02-16 21:28 UTC by khaled106

Created SignIn/SignUp Page
There is still a bug to be fixed in the css ("A new issue wil be created for this") 
Now the data will be stored in the console.

2023-02-16 21:38 UTC, ramy-att requested changes
There is a lot of commented-out code we can just remove that. The functionality looks great! I will create an issue for the small bug on the label's transition and spacing

2023-02-16 21:38 UTC, ramy-att commented on client/src/components/SignIn/SignIn.css
> +/* } */
@khaled106 can you please remove all commented out code

2023-02-16 21:38 UTC, ramy-att commented on client/src/components/SignUp/SignUp.css
> +/*    */
We can remove extra comments

2023-02-16 21:47 UTC, khaled106 commented on client/src/components/SignUp/SignUp.css
> +/*    */
Done

2023-02-16 21:54 UTC, khaled106 commented
@ramy-att  I removed the unnecessary comments, you can check over the code again and merge to master if it's good.
Thanks Ramy !!

2023-02-16 22:37 UTC, ramy-att approved these changes
Looks amazing.

2023-02-17 01:20 UTC, ramy-att commented
> @ramy-att I removed the unnecessary comments, you can check over the code again and merge to master if it's good. Thanks Ramy !!

Looks good

2023-02-17 01:22 UTC, merged