Edit page
ramy-att/trivial-soen341project2023 pull request #36
Opened 2023-02-16 22:36 UTC by Ziad-Tari

I created a profile edit page so the user can edit and add the required information.

2023-02-18 00:20 UTC, ramy-att requested changes
We need to add the student and employer options. @Ziad-Tari let me know when you are done and need help with the CSS, please.

2023-02-20 16:32 UTC, ramy-att commented
@mario-elshaer @khaled106 added you as reviewers if you want to check the page and code! Thanks

2023-02-20 16:38 UTC, khaled106 commented on client/package.json
> +    "react-scripts": "^5.0.1",
Keep the one from Master. Pull from master and commit the changes they suggested

2023-02-20 16:39 UTC, khaled106 commented on client/src/App.js
> -import { Route } from "react-router-dom";
You need to pull from master first before making a Pull Request

2023-02-20 16:40 UTC, khaled106 commented on client/src/App.js
> +import Editprofile from "./pages/EditProfile";
Make sure that all the imports in the master are here as well as the one you added!

2023-02-20 16:42 UTC, khaled106 requested changes
Make sure that you pull from origin first as some code are missing and this will cause a conflict

2023-02-20 20:39 UTC, ramy-att commented
> Make sure that you pull from origin first as some code are missing and this will cause a conflict

@Ziad-Tari Please fix the pages and components in their correct files, pull the latest version of the project and push again with the issues resolved
@khaled106 thanks for your reviewing!

2023-02-21 22:04 UTC, ramy-att requested changes

2023-02-21 22:04 UTC, ramy-att commented on client/src/components/EditPage/EditPage.js
> +            </Form.Group>
We should allow the user to have a default transcript too

2023-02-26 02:46 UTC, ramy-att commented
@Ziad-Tari It would make sense for us to complete #42 in this branch as well before merging. Please fix all the prior issues in the pr and try to complete #42. Let me or @khaled106 or @mario-elshaer know if you have any problems!

2023-02-28 22:57 UTC, khaled106 approved these changes
Good Work!! Thanks Ziad!!

2023-02-28 23:01 UTC, ramy-att approved these changes

2023-02-28 23:04 UTC, merged