Employer,postings and application   models  schemas  routes
ramy-att/trivial-soen341project2023 pull request #49
Opened 2023-02-19 00:54 UTC by MazennW

Regarding Issue #13 
The backend for employers, postings and applications have been implement.

Currently you are capable of creating, adding, deleting or updating any of the mentioned objects.
Please take a look and review my code and let me know if anything's not right.

2023-02-20 02:05 UTC, ramy-att requested changes

2023-02-20 02:06 UTC, MazennW commented on server/model/employer.js
> +    name:{
I will fix that

2023-02-20 02:11 UTC, MazennW commented on server/model/employer.js
> +
Storing an array in MongoDB might be a little tricky, so a quick fix for that might be to store comma separated strings that act as reference to each ID, however this might not be optimal unless we can figure a fix for it.

2023-02-20 02:57 UTC, ramy-att commented
Confirmation of the changes that will be done:

-> Instead of creating array structures in the database we will store ids in a comma-separated-values string and will create a helper controller to allow the data to be returned to the front-end
-> Students should have access to their applications (comma-separated-values string attribute of the IDs) + controller to fetch the applications by the ID - this reduces the time complexity 
-> Employers will have access to postings through the same methods
-> Applications are a part of postings

* Based on conversation with Mazen 
* Changes will be made to the database.txt doc file to reflect this - I will create an issue for this

cc @MazennW

2023-02-20 20:54 UTC, ramy-att approved these changes
Can you please just add the transcript, looks good! @MazennW

2023-02-20 20:54 UTC, ramy-att commented on server/model/application.js
> +
@MazennW can you please add the transcript

2023-02-25 20:37 UTC, ramy-att approved these changes

2023-02-25 20:37 UTC, merged